# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Basic metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_ENV }}

          # Options
          user: fn-jakubkarp
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
