name: Render rss - software engineering daily
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}

          # Options
          filename: metrics.plugin.rss.svg
          base: ""
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: "https://softwareengineeringdaily.com/feed/"
